version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=adminuser
      - POSTGRES_DB=users
    networks:
      - backend
  redis:
    image: redis:alpine
    ports:
      - "5432:5432"
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - backend

networks:
    backend: