version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=ZXbEqJoiH2j1YKvUCRyuT5wK1UGJCUVE"
      - "POSTGRES_USER=users_admin"
      - "POSTGRES_DB=users_db"
    networks:
      - backend
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - backend

networks:
    backend:
